// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
...e4f444eef............
...4df2222f4e...........
...44f2222fd4...........
....f45544f44...........
....ffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . e e e e e e e e e e . . 
. . . . e e e f f e e e e e . . 
. . . . e e e e f e e e e e . . 
. . . . e e e f f f e e e e . . 
. . . . e e e e e e e e e e . . 
. . . . e e e e e e e e e e . . 
. . . . e e e e e e e e 5 e . . 
. . . . e e e e e e e e e e . . 
. . . . e e e e e e e e e e . . 
. . . . e e e e e e e e e e . . 
. . . . e e e e e e e e e e . . 
. . . . e e e e e e e e e e . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
