namespace SpriteKind {
    export const door = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.door, function (sprite, otherSprite) {
	
})
let soilder = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    ...e4f444eef............
    ...4df2222f4e...........
    ...44f2222fd4...........
    ....f45544f44...........
    ....ffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(soilder)
let door_1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . e e e e e e e e e e . . 
    . . . . e e e f f e e e e e . . 
    . . . . e e e e f e e e e e . . 
    . . . . e e e f f f e e e e . . 
    . . . . e e e e e e e e e e . . 
    . . . . e e e e e e e e e e . . 
    . . . . e e e e e e e e 5 e . . 
    . . . . e e e e e e e e e e . . 
    . . . . e e e e e e e e e e . . 
    . . . . e e e e e e e e e e . . 
    . . . . e e e e e e e e e e . . 
    . . . . e e e e e e e e e e . . 
    `, SpriteKind.door)
door_1.setPosition(7, 54)
scene.setBackgroundColor(1)
